### ISSUE TITLE
Add support for display names

### ISSUE THREAD

**Issue by QuillLittlefeather** [InWorldz/halcyon#254]
In viewer i click to change displayname and it says it failed. I looked in the halcyon code and i see that it should be able to handle setting display names.  is this a bug?

**Comment by jimtarber** [comment]
It's not implemented (at all). There are some small stubs in the LSL handling so that the LSL functions related to display names still do something reasonable, but there's no support at all for display names currently in Halcyon.  However, we can consider the issue raised, and feature requested, now in this issue #254.

**Comment by kf6kjg** [comment]
This issue was moved to HalcyonGrid/halcyon#9
