### ISSUE TITLE
i  did try  several codes  all  seems  to  miss  something. 

### ISSUE THREAD

**Issue by Xantis** [InWorldz/halcyon#414]
Hello Inworldz,
I did try  several  things and everytime with another code  I  have another  log with the  same .ini  file 
This is the last  log :
[halcyon.log](https://github.com/InWorldz/halcyon/files/1541039/halcyon.log)
And this  is  the  last .INI
[halcyon.ini.txt](https://github.com/InWorldz/halcyon/files/1541041/halcyon.ini.txt)

Any help is welcome as  I  am on the end of thinking, it  just does not work, I  notice that  everytime it can not  locate a  file while it is  there, and  sometime its  really  not there, I  mean this is  not even GRID MODE  but Stand Alone, can someone  tell  me  just what  to  do to  get it  up and working?

With respect,
Frans Orbis

**Comment by kf6kjg** [comment]
Looks like you've configured Halcyon to use WHIP for your assets, but don't
have WHIP running.  If WHIP is running, it might be blocked by your
firewall.

BTW, you should scrub passwords before uploading config files.

**Comment by kf6kjg** [comment]
Frans, were you able to solve the issue?

**Comment by appurist** [comment]
I think something similar was just posted in the forum discussion (with passwords again that are somewhat similar, so I suspect a followup attempt).

Frans, all reports of trouble starting Halcyon servers should be in this Issues page on GitHub, as that's where the development team is reading.

I'm hoping this reply reaches you, as we are here to help.

As was mentioned above, the post above looks like the WHIP asset server was not running (it must be started before the Halcyon components).  The post in the forum looks like the PhysX.NET dll was missing (which is strange since it is provided in the bin folder in this repository), or that perhaps the Halcyon executables were built as a 32-bit version, which I'm not even sure is possible.  It must be built as a 64-bit build, and I usually build the Debug version (even for production use).

The second error in the forum post is for the OpenSim.Data.MySQL dll, which is one of the targets built by the Halcyon solution (.sln) file.

Is it possible that only the Halcyon target is being built? It should be set as the startup project, but the whole solution should be built (all DLLs and targets).  

Another assumption to verify here: Visual Studio 2015 or 2017 should be used, and runprebuild.bat should be run prior to starting, as that produces the .sln solution and project files.

Anyhow, hopefully any current issues building will get posted here so we can help.
