### ISSUE TITLE
IAR

### ISSUE THREAD

**Issue by Ana-Green** [InWorldz/halcyon#423]
**IAR**

First of all, we just got Halcyon up and just two regions active me still being a cloud because there is not even a default avatar available. Then I was amazed that there was for "the Grid Owner" no option to import / export inventory files, like the compressed files.iar. Then Vin told me to put my avatar in a  box (prim) and put that on an empty land then upload the whole land as OAR what seems to work, so IAR does not work but OAR does work fuzzy logic?

I reported already this :
2018-02-17 18:24:17,968 [ConsoleThread] ERROR OpenSim.Region.CoreModules.ServiceConnectors.User.LocalUserServicesConnector - [USER CONNECTOR]: UserService missing from Halcyon.ini
2018-02-17 18:24:17,984 [ConsoleThread] ERROR OpenSim.Region.CoreModules.Asset.CoreAssetCache - [ASSET CACHE]: AssetCache missing from Halcyon.ini

As I thought it had to do with it seems not  Vin said it would be gone later but it's still there. Inworldz has the option to provide any user on request an IAR file so  he/she can keep that  file on their  home  computer in case the  inventory  would get corrupt  then send it  back to the support team because 'so it seems' they are able  to upload this IAR file to restore/replace the inventory (repair the  inventory  if  

you  like).  https://inworldz.com/ssinvbak.php

Self-Service Inventory Backup
On this page, you can submit a request for a self-serve inventory backup file to be produced for download to your computer. 

This file can be saved on your computer as a backup and sent in to Support if you later have inventory troubles or accidentally delete items from your inventory. Support may be able to use this backup to restore some or all of your lost items to your inventory. 
Please note that support will investigate but may not restore no-copy items without finding evidence of a system error. 

To replace no-copy items you may have accidentally deleted or lost, please first contact the vendor of the item to check whether a new copy of the item can be provided to you. 
Click here to request a backup of your inventory
Or is only inworldz able to perform that operation and all other released codes do not have that build in or disabled? That's  just a question.

As  last I have another  grid  up and "New users" can choose an avatar, I believe  it is 12 for male and 12 for  female, why  well  users  will press push, pull the plug  if they only can run around as some  smoke and  not able to create  "even a noob avatar" as that seems  the case right  now. 
All grids have some sort of backup system "yes also Second Life" why has  IAR be disabled for  Grid Owners? Then using God Powers Level 200 does not show that you are in God mode if you are in God mode as Grid Owner.

There is a lot more but these points are important.

Best regards,
Ana Green

**Comment by appurist** [comment]
Just to clarify the above, there are many inventory differences between InWorldz and OpenSim, and there are some aspects of inventory that even differ between InWorldz (specific) and Halcyon (generic).

InWorldz stores inventory in Apache Cassandra, while generally-speaking, Halcyon grids do not bother to set this up.  Even if they did, InWorldz is a closed/secure grid and the self-serve inventory backup is not a user-serviceable feature, it is only an encrypted _backup_ (not an export) of the user's current InWorldz inventory suitable only for use by InWorldz Support staff, it is not a general export/import facility.  There is nothing disabled in the Halcyon code, it just doesn't exist at all in the Halcyon code (even at InWorldz).  It is only a feature of the InWorldz _website_ code, not a feature of the Halcyon grid services and region servers.  There is also no support in Halycon for inventory (IAR) export or import.  There is however viewer-side support for export/import of rezzed objects and their contents, so that is why this was suggested.
