### ISSUE TITLE
Defining gridmode = false in Halcyon.ini seems to treat it as true

### ISSUE THREAD

**Issue by To-mos** [InWorldz/halcyon#440]
I was having trouble getting my server to boot under standalone mode, below [Startup] I had uncommented the `;gridmode = false` line assuming grid mode would be off. After I did, I kept getting `no default region available` when an avatar would try and connect. Changing it to `gridmode = true` would result in the same error message. The only way I fixed it was commenting the line back out. This does not seem like the desired behavior.

**Comment by appurist** [comment]
I just checked, the default is false, so commenting it out or leaving it in as `gridmode = false` should be the same.

We run with `gridmode = true` everywhere I know, including my home test server, but the requirements are more complex in grid mode: you must run User, Grid and Messaging "central grid services", in that order, prior to starting the actual Halcyon.exe region server.

The error above means that the user record's home region coordinates are not valid (or the region is down, or the region has not communicated with the grid service to notify it's up, or the Grid service isn't running).

If the Grid service is up (and I assume it is since it seems like User is up and responding with this error), then check your database `users` records for a user account that matches what you're logging in with, and check the `homeRegion` column for their home region handle. Typically that is `1099511628032000` which in hexadecimal is `3E8000003E800`, which corresponds to the grid map location `1000,1000`.  Is your region up and running, with those coordinates (default welcome region coordinates)?

**Comment by kf6kjg** [comment]
@To-mos It almost seems like you haven't defined any regions in the `bin/Regions` folder.

**Comment by kf6kjg** [comment]
I've not tested, but I'd expect that a region would have to be defined in order for even standalone to run.

**Comment by kf6kjg** [comment]
@To-mos If this is still an issue could you re-open on the new location for Halcyon? https://github.com/HalcyonGrid/halcyon/issues

Thank you.
