### ISSUE TITLE
What's WhisperVoice?

### ISSUE THREAD

**Issue by kf6kjg** [InWorldz/halcyon#54]
The code is somehow loading it, and is (because of some changes I'm working on) no longer running on my local copy because WhisperVoice isn't able to be loaded for some reason.  My question is: what is/was it, and is it needed any more?

**Comment by jimtarber** [comment]
Whisper is an alternative to Vivox for in-world voice. See Mumble/Murmur https://en.wikipedia.org/wiki/Mumble_%28software%29 

We don't use it in InWorldz (we use Vivox) and I'm not sure what state the Whisper code is in. The last update was December 2011. 

SL uses Vivox, so providing Vivox-based in-world voice also added more compatibility with SL.

In January 2012, we adopted Vivox instead, after we negotiated a license. Also at that time, Vivox began offering free service for small OpenSim grids: https://support.vivox.com/opensim/

The Halcyon project has a philosophy of removing redundant options for various subsystem implementations and going with the best available solutions for each component. So as far as I know, at least for the foreseeable future, we have no intention of supporting Vivox. I believe it's still there because some work was done initially to support Whisper and it's just saving that effort.

**Comment by kf6kjg** [comment]
I'm sure "we have no intention of supporting Vivox." has a typo. :P

Ok, so removing those files wasn't an issue.  Not sure where they came from in my working copy, but the current tree doesn't seem to have them or any of their supporting files anyway.

Thanks!
