### ISSUE TITLE
In-sim asset cache pruning

### ISSUE THREAD

**Issue by ddaeschler** [InWorldz/halcyon#60]
We should periodically (every 5 minutes?) prune the in-sim memory based asset cache so that we can set the per-sim values higher.

**Comment by jimtarber** [comment]
I actually think 128 is pretty reasonable there. Especially since that's not 128 objects, it's *unreferenced* uses of 128 *different* scripts.  The problem starts at 1, and I think any region is unlikely to have more than a dozen such cases, except for extreme edge cases like stores with rezzers for all products that may have 100 such rezzers or more, i.e. probably not more than 1 such region grid-wide.  As long as the cache is LRU (and it is), and 128 isn't an excessive amount of memory (it isn't), I don't see the 128 limit as problematic at all. It may even be overly-generous.

That said, it would be nice to free up the memory after a time period anyway, if it wasn't used, rather than just keeping it around indefinitely until something new forces it out, especially if what I said above is accurate because in that case it's also likely that nothing will force it out and the memory will remain in use until restart.

**Comment by ddaeschler** [comment]
This is a request for the asset cache not the script cache. The asset cache can get up to 96 MB on our new configuration in busy regions and l'd like that trimmed when the region goes idle

**Comment by jimtarber** [comment]
Indeed, I was referring to the new "removed scripts" cache. ;)

Pruning the asset cache is obviously even more important, and pruning it would allow us to increase the cache sizes, to handle larger short-term bursts. I like.

**Comment by mdickson** [comment]
I have a working aged LRU cache along with a test that verifies the cleanup after the age is passed.  I can clearly see ways to optimize but I think I'll push it up and do a pull request and I can optimize a bit in a second batch of work.   I did add locking since there is a timer thread now that can access things OOB.  So when reviewing give that extra scrutiny.

**Comment by ddaeschler** [comment]
This is partially addressed by PR #67

**Comment by ddaeschler** [comment]
Added this in the buffer pool. Just needs the maintenance timers hooked up

**Comment by ddaeschler** [comment]
This is all set
